### ISSUE TITLE
PHASE 2 API Productions 

### ISSUE THREAD

**Issue by meenalsar008** [meenalsar008/SoftwareEngineeringCSYE7230#34]
Issue Summary:
Phase 2 Production introduced critical features to enhance the Northeastern Medication platform. This Github issue is created to track the development and address any potential challenges related to the new features implemented during this phase.

New Features:

 - [x] Search Nearby Stores:
Description: Improved user accessibility by enabling the search for nearby pharmacies, enhancing the convenience of locating medical assistance.

 - [x] Chatbot for User Assistance:
Description: Implemented a chatbot feature to provide real-time assistance to users, fostering a more interactive and user-friendly experience.

 - [x] Add Products and Add Categories:
Description: Expanded platform capabilities by allowing Admin to seamlessly add new products to the inventory and categorize them for improved organization.

 - [x] Make Payment:
Description: Introduced a secure payment feature, enabling users to complete transactions seamlessly within the platform.

 - [x] User Registration:
Description: Implemented a user registration system, providing users with personalized accounts for a more tailored experience.

Additional Information:
Any dependencies or issues that might affect the completion of the features.
Any specific testing criteria or scenarios that need to be considered.

**Comment by meenalsar008** [comment]
User Registration Done

**Comment by yash-sah** [comment]
Phase 2 Completed
