### ISSUE TITLE
Enable CI/CD Pipeline

### ISSUE THREAD

**Issue by yash-sah** [meenalsar008/SoftwareEngineeringCSYE7230#8]
User Story
As a developer, I would like to be able to deploy the website to heroku easily so that the rest of the team can start developing.

Detailed Description
The repository should be setup to enable CI/CD using Heroku Pipelines and review apps. Heroku Review apps will enable CI by automatically creating test environments for new pull request. The pull request can be denied or accepted based on the testing in the review app. Whenever a branch initiates a pull request it should automatically build the master branch, and launch the branch in a new test environment.

Acceptance Criteria

- [x]  Given that I am a developer on the team, I can code my feature, then deploy to Heroku without any configuration or environment issues.
- [x]  Given A developer creates a pull request with the master branch, then A new Heroku review app is created to launch the merged pull request in a test environment
- [x]  Given A developer creates a new production environment on Heroku with any branch, then The branch should automatically build before launching

**Comment by SankalpRaptorAwasthi** [comment]
Adding the Client changes on the Fly then ! CI CD optimization's commits

**Comment by yash-sah** [comment]
Done and Tested
