### ISSUE TITLE
Add Frontend Testing

### ISSUE THREAD

**Issue by yash-sah** [meenalsar008/SoftwareEngineeringCSYE7230#9]
User Story
As a Developer, I would like a frontend testing framework so that I can set up tests that run when I compile the code.

Detailed Description
Provide additional details and context.

Acceptance Criteria

- [x]  Given I add more code, then I can easily add new test cases for it
- [x]  Given I test the frontend, at least a few modules will have tests run for it

**Comment by meenalsar008** [comment]
Tested by Sankalp
